/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123884-gd3d0b7a5ee-20260409"
#endif /* AVUTIL_FFVERSION_H */
