- name: Download & Extract FFmpeg (Windows)
      if: runner.os == 'Windows'
      run: |
        curl -L -o ffmpeg.zip ${{ matrix.ffmpeg_url }}
        # Флаг -y отвечает "Да" на любые вопросы архиватора, -o создает папку temp_win
        7z x ffmpeg.zip -y -otemp_win
        mkdir -p dist/Alfeonull_Studio/ffmpeg/bin
        cp temp_win/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe dist/Alfeonull_Studio/ffmpeg/bin/

    - name: Download & Extract FFmpeg (macOS)
      if: runner.os == 'macOS'
      run: |
        curl -L -o ffmpeg.zip ${{ matrix.ffmpeg_url }}
        # Флаг -o перезаписывает без вопросов, -d кидает файлы во временную папку
        unzip -o ffmpeg.zip -d temp_mac
        mkdir -p dist/Alfeonull_Studio/ffmpeg/bin
        cp temp_mac/ffmpeg dist/Alfeonull_Studio/ffmpeg/bin/
        chmod +x dist/Alfeonull_Studio/ffmpeg/bin/ffmpeg

    - name: Download & Extract FFmpeg (Linux)
      if: runner.os == 'Linux'
      run: |
        curl -L -o ffmpeg.tar.xz ${{ matrix.ffmpeg_url }}
        mkdir -p temp_linux
        tar -xf ffmpeg.tar.xz -C temp_linux
        mkdir -p dist/Alfeonull_Studio/ffmpeg/bin
        cp temp_linux/ffmpeg-*-static/ffmpeg dist/Alfeonull_Studio/ffmpeg/bin/
        chmod +x dist/Alfeonull_Studio/ffmpeg/bin/ffmpeg

    - name: Assemble Portable Folder
      shell: bash
      run: |
        # Копируем папку app (шаблоны, статика) к собранному проекту
        cp -r app dist/Alfeonull_Studio/
