name: Build Portable Studio

on:
  workflow_dispatch: # Запуск по кнопке "Run workflow"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: Alfeonull_Studio_Windows
            ffmpeg_url: "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
            
          - os: macos-latest
            artifact_name: Alfeonull_Studio_Mac
            ffmpeg_url: "https://evermeet.cx/ffmpeg/getrelease/zip"
            
          - os: ubuntu-latest
            artifact_name: Alfeonull_Studio_Linux
            ffmpeg_url: "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Executable (PyInstaller)
      shell: bash
      run: pyinstaller --noconsole --name "Alfeonull_Studio" run.py

    - name: Download & Extract FFmpeg (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl -L -o ffmpeg.zip ${{ matrix.ffmpeg_url }}
        # Распаковываем во временную папку temp_win, перезаписывая без вопросов (-y)
        7z x ffmpeg.zip -y -otemp_win
        mkdir -p dist/Alfeonull_Studio/ffmpeg/bin
        cp temp_win/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe dist/Alfeonull_Studio/ffmpeg/bin/

    - name: Download & Extract FFmpeg (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -L -o ffmpeg.zip ${{ matrix.ffmpeg_url }}
        # Распаковываем во временную папку temp_mac
        unzip -o ffmpeg.zip -d temp_mac
        mkdir -p dist/Alfeonull_Studio/ffmpeg/bin
        cp temp_mac/ffmpeg dist/Alfeonull_Studio/ffmpeg/bin/
        # Обязательно даем права на исполнение!
        chmod +x dist/Alfeonull_Studio/ffmpeg/bin/ffmpeg

    - name: Download & Extract FFmpeg (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -L -o ffmpeg.tar.xz ${{ matrix.ffmpeg_url }}
        mkdir -p temp_linux
        tar -xf ffmpeg.tar.xz -C temp_linux
        mkdir -p dist/Alfeonull_Studio/ffmpeg/bin
        # Используем подстановочный знак для папки версии
        cp temp_linux/ffmpeg-*-static/ffmpeg dist/Alfeonull_Studio/ffmpeg/bin/
        # Даем права на исполнение
        chmod +x dist/Alfeonull_Studio/ffmpeg/bin/ffmpeg

    - name: Assemble Portable Folder
      shell: bash
      run: |
        # Копируем папку app (шаблоны, статика, пресеты) к собранному проекту
        cp -r app dist/Alfeonull_Studio/

    - name: Upload Artifacts (ZIP)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/Alfeonull_Studio/
